const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Books collection and inserts the books below

mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/birders"
);

const birdSeed = [
  {
    email:"lylekarim+1@gmail.com",
    password:"password",
    initial: "S",
    lastName: "Malone",
    area: "Alexandria",
    state: "VA",
    available: "Anytime",
    interests: "Lister",
    language: "English",
    description: "The Northern Virginia area has diverse habitats which make it a good birding destination year around.",
    comments: "The Northern Virginia area has diverse habitats which make it a good birding destination year around.",
    title: "BRucker",
    author: "BRucker",
    thumbnail: "",
    reviews: 1
  },
  {
    email:"lylekarim+2@gmail.com",
    password:"password",
    initial: "E",
    lastName: "Serlin",
    area: "Alexandria",
    state: "VA",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English",
    description: "The Northern Virginia area has diverse habitats which make it a good birding destination year around.",
    comments: "I am fortunate to live near some nice spring migration spots especially for warblers. Then there are the Blue Ridge Mnts. nearby.",
    title: "SMalone",
    author: "SMalone",
    thumbnail: "assets/images/birdsplash/aditya-sethia-1244414-unsplash.png",
    reviews: 2
  },
  {
    email:"lylekarim+3@gmail.com",
    password:"password",
    initial: "F",
    lastName: "Marenghi",
    area: "Annapolis",
    state: "MD",
    available: "Weekend",
    interests: "Birding by Ear",
    language: "English",
    description: "Annapolis is on the Chesapeake Bay, a 45 minute drive from Washington DC and Baltimore, an hour and half to the Delaware Bay, and 2 hours to the Atlantic Ocean. I work Monday through Friday but spend many weekends and holidays birding locally or within the region. Best birding here is late Summer through Spring.",
    comments: "",
    title: "ECarlson",
    author: "ECarlson",
    thumbnail: "assets/images/birdsplash/adli-wahid-1161669-unsplash.png",
    reviews: 3
  },
  {
    email:"lylekarim+4@gmail.com",
    password:"password",
    initial: "D",
    lastName: "Grosboll",
    area: "Asheville",
    state: "NC",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "I have been an active birder for thirty years. I would consider myself an expert on local birding topics. I feed the birds at my house with every feed our local birds might need.",
    comments: "",
    title: "MHillman",
    author: "MHillman",
    thumbnail: "assets/images/birdsplash/alex-shutin-204336-unsplash.png",
    reviews: 4
  },
  {
    email:"lylekarim+5@gmail.com",
    password:"password",
    initial: "D",
    lastName: "Johnston",
    area: "Asheville",
    state: "NC",
    available: "Anytime",
    interests: "Warblers",
    language: "English",
    description: "Know some good sites in the Blue Ridge mountains and surrounding area.",
    comments: "I live in the Pisgah National Forest and love to bird all over the area: Grandfather Mountain, Table Rock NC and surrounding areas. I put anytime as available, but only because I have some times during the week and weekend free.",
    title: "SSemanchuk",
    author: "SSemanchuk",
    thumbnail: "assets/images/birdsplash/alexandre-debieve-212961-unsplash.png",
    reviews: 1
  },
  {
    email:"lylekarim+6@gmail.com",
    password:"password",
    initial: "S",
    lastName: "Semanchuk",
    area: "Asheville, North Carolina",
    state: "NC",
    available: "Anytime",
    interests: "Photography",
    language: "English",
    description: "I am fortunate to live near some nice spring migration spots especially for warblers. Then there are the Blue Ridge Mnts. nearby.",
    comments: "Know some good sites in the Blue Ridge mountains and surrounding area.",
    title: "DGrosboll",
    author: "DGrosboll",
    thumbnail: "assets/images/birdsplash/alistair-dent-55440-unsplash.png",
    reviews: 3
  },
  {
    email:"lylekarim+7@gmail.com",
    password:"password",
    initial: "B",
    lastName: "Klick",
    area: "Baltimore",
    state: "MD",
    available: "Anytime",
    interests: "Hiking",
    language: "English, Mandarin",
    description: "Not the best place in United States, but is good during spring and fall migration.",
    comments: "",
    title: "RJohnson",
    author: "RJohnson",
    thumbnail: "assets/images/birdsplash/anders-nord-459835-unsplash.png",
    reviews: 4
  },
  {
    email:"lylekarim+8@gmail.com",
    password:"password",
    initial: "H",
    lastName: "Anu",
    area: "Baltimore",
    state: "MD",
    available: "Anytime",
    interests: "Warblers",
    language: "English",
    description: "Know some good sites in the Blue Ridge mountains and surrounding area.",
    comments: "",
    title: "FMarenghi",
    author: "FMarenghi",
    thumbnail: "assets/images/birdsplash/andre-mouton-193050-unsplash.png",
    reviews: 5
  },
  {
    email:"lylekarim+9@gmail.com",
    password:"password",
    initial: "J",
    lastName: "Landers",
    area: "Baltimore",
    state: "MD",
    available: "Anytime",
    interests: "Photography",
    language: "English",
    description: "I have served on the Southern Maryland Audubon Society Board on two occasions and am currently a member of the education committee. I have participated in May and Christmas counts for over 15 years. I would be happy to give locations information and when I can accompany them to local areas. I live in Charles County with border on the Potomac River. It contains various creeks, swamps, streams and ponds. Several wildlife management areas/state parks in my area.",
    comments: "I have served on the Southern Maryland Audubon Society Board on two occasions and am currently a member of the education committee. I have participated in May and Christmas counts for over 15 years. I would be happy to give locations information and when I can accompany them to local areas. I live in Charles County with border on the Potomac River. It contains various creeks, swamps, streams and ponds. Several wildlife management areas/state parks in my area.",
    title: "HAnu",
    author: "HAnu",
    thumbnail: "assets/images/birdsplash/andrea-reiman-251037-unsplash.png",
    reviews: 1
  },
  {
    email:"lylekarim+10@gmail.com",
    password:"password",
    initial: "M",
    lastName: "Dodson",
    area: "Baltimore",
    state: "MD",
    available: "Weekend",
    interests: "Rare Birds",
    language: "English",
    description: "I work for The Nature Conservancy and I'm knowledgeable about public and privately protected conservation areas in North Carolina. I live in the Blue Ridge Mountains of northwestern NC and I'm available to help birders in the mountain region of northwestern NC and adjoining parts of northeastern TN, and southwestern VA.",
    comments: "I am a retired birder in Maryland who would be available to take travelers birding in the Baltimore area. I have been birding most of my life. I can take birders during day trips.",
    title: "KHarris",
    author: "KHarris",
    thumbnail: "assets/images/birdsplash/andrea-reiman-270997-unsplash.png",
    reviews: 5
  },
  {
    email:"lylekarim+11@gmail.com",
    password:"password",
    initial: "M",
    lastName: "Brazeau",
    area: "Baltimore",
    state: "MD",
    available: "Anytime",
    interests: "Birding by Ear",
    language: "English, A Little Spanish",
    description: "I am a retired birder in Maryland who would be available to take travelers birding in the Baltimore area. I have been birding most of my life. I can take birders during day trips.",
    comments: "",
    title: "MDodson",
    author: "MDodson",
    thumbnail: "assets/images/birdsplash/andrew-alexander-88432-unsplash.png",
    reviews: 5
  },
  {
    initial: "L",
    lastName: "Lampley",
    area: "Banner Elk",
    state: "NC",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "I live in the Pisgah National Forest and love to bird all over the area: Grandfather Mountain, Table Rock NC and surrounding areas. I put anytime as available, but only because I have some times during the week and weekend free.",
    comments: "",
    title: "DJohnston",
    author: "DJohnston",
    thumbnail: "assets/images/birdsplash/andrew-pons-57133-unsplash.png",
    reviews: 4
  },
  {
    initial: "D",
    lastName: "Moulton",
    area: "Bethesda",
    state: "MD",
    available: "Weekdays",
    interests: "Hiking",
    language: "English",
    description: "I lead trips for the Southern Maryland Audubon Society. I am very experienced with bird-finding in this region, which is a wonderful birding area. I know what a tremendous help it has been to me to have a local guide in new territory. I hope I can help.",
    comments: "The Eastern Shore of Maryland and Delaware, Blackwater National Wildlife Refuge (Bald Eagle capital of E. North America). I am an avid Wildlife photographer with an interest is birds.",
    title: "CPerera",
    author: "CPerera",
    thumbnail: "assets/images/birdsplash/andy-chilton-108628-unsplash.png",
    reviews: 3
  },
  {
    initial: "J",
    lastName: "Lindenberger",
    area: "Blowing Rock (summer only)",
    state: "NC",
    available: "Anytime",
    interests: "Warblers",
    language: "English, German, Hebrew, Spanish",
    description: "I am a single parent and retired Army. I live in a neighborhood, that used to be home to some 96 species of birds, so far, I've seen and heard since I moved here. I'm pretty good at bird calls having called in about seven species to include the Barred Owl, Collared Dove and a Hooded Warbler.",
    comments: "I work for The Nature Conservancy and I'm knowledgeable about public and privately protected conservation areas in North Carolina. I live in the Blue Ridge Mountains of northwestern NC and I'm available to help birders in the mountain region of northwestern NC and adjoining parts of northeastern TN, and southwestern VA.",
    title: "LLampley",
    author: "LLampley",
    thumbnail: "assets/images/birdsplash/asdrubal-luna-485612-unsplash.png",
    reviews: 3
  },
  {
    initial: "J",
    lastName: "Lynch",
    area: "Boone",
    state: "",
    available: "Weekend",
    interests: "Photography",
    language: "English",
    description: "I work for The Nature Conservancy and I'm knowledgeable about public and privately protected conservation areas in North Carolina. I live in the Blue Ridge Mountains of northwestern NC and I'm available to help birders in the mountain region of northwestern NC and adjoining parts of northeastern TN, and southwestern VA.",
    comments: "I am a single parent and retired Army. I live in a neighborhood, that used to be home to some 96 species of birds, so far, I've seen and heard since I moved here. I'm pretty good at bird calls having called in about seven species to include the Barred Owl, Collared Dove and a Hooded Warbler.",
    title: "JLindenberger",
    author: "JLindenberger",
    thumbnail: "assets/images/birdsplash/bartosz-kwitkowski-1268101-unsplash.png",
    reviews: 4
  },
  {
    initial: "T",
    lastName: "McGreal",
    area: "Cameron",
    state: "NC",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English",
    description: "I am a single parent and retired Army. I live in a neighborhood, that used to be home to some 96 species of birds, so far, I've seen and heard since I moved here. I'm pretty good at bird calls having called in about seven species to include the Barred Owl, Collared Dove and a Hooded Warbler.",
    comments: "I'm happy to show folks birds in the area or slightly further afield. Red-cockaded Woodpeckers and Bachman's Sparrows within an hour's drive, excellent wintering birds in eastern Carolina further.",
    title: "JLynch",
    author: "JLynch",
    thumbnail: "assets/images/birdsplash/bill-williams-14506-unsplash.png",
    reviews: 1
  },
  {
    initial: "N",
    lastName: "Swick",
    area: "Chapel Hill",
    state: "NC",
    available: "Anytime",
    interests: "Birding by Ear",
    language: "English",
    description: "I'm happy to show folks birds in the area or slightly further afield. Red-cockaded Woodpeckers and Bachman's Sparrows within an hour's drive, excellent wintering birds in eastern Carolina further.",
    comments: "If you want a young, energetic, expert guide who can help you locate/identify/photograph birds/butterflies and any other wildlife in North Carolina, I am the man for the job. Send me a hit list and I'll tell you where we can go.",
    title: "TMcGreal",
    author: "TMcGreal",
    thumbnail: "assets/images/birdsplash/bill-williams-17163-unsplash.png",
    reviews: 2
  },
  {
    initial: "A",
    lastName: "Kneidel",
    area: "Chapel Hill",
    state: "NC",
    available: "Anytime",
    interests: "Hiking",
    language: "English, fluent Spanish",
    description: "If you want a young, energetic, expert guide who can help you locate/identify/photograph birds/butterflies and any other wildlife in North Carolina, I am the man for the job. Send me a hit list and I'll tell you where we can go.",
    comments: "",
    title: "NSwick",
    author: "NSwick",
    thumbnail: "assets/images/birdsplash/bill-williams-20560-unsplash.png",
    reviews: 3
  },
  {
    initial: "M",
    lastName: "Cooper",
    area: "Charlotte",
    state: "NC",
    available: "Weekend",
    interests: "Warblers",
    language: "English",
    description: "I am not an expert but serve on our local Audubon board with a lot of them! If there is a specific bird or birds that you would like to see I am sure I can find out where to go. I am in the Raleigh/Durham area (middle of the state). We have lots of very cool birds.",
    comments: "I am not an expert but serve on our local Audubon board with a lot of them! If there is a specific bird or birds that you would like to see I am sure I can find out where to go. I am in the Raleigh/Durham area (middle of the state). We have lots of very cool birds.",
    title: "AKneidel",
    author: "AKneidel",
    thumbnail: "assets/images/birdsplash/boris-smokrovic-131485-unsplash.png",
    reviews: 4
  },
  {
    initial: "S",
    lastName: "Gill",
    area: "Charlottesville",
    state: "VA",
    available: "Weekend",
    interests: "Photography",
    language: "English",
    description: "I am fortunate to live near some nice spring migration spots especially for warblers. Then there are the Blue Ridge Mnts. nearby.",
    comments: "I live in an area where there are small towns. Blacksburg and Christiansburg and Radford, Virginia. Blacksburg is the home of the largest University in the State. Radford is the host to a smaller University, Radford. As Radford parallels New River there are ample opportunities to bird in our area. There are also birding trails in both Blacksburg and in Radford. These are a part of the Virginia Birding trail system. I have a small Jon boat and I am willing to take a fellow birder on a river trip. However I will not be interested in taking any person birding who smokes. I am an avid bird watcher as well as a photographer. When I go on trips I will always take a camera with me. I will always be more than willing to answer any inquiries that folks would like to know about the area where I live. I belong to the New River Bird Club and have many friends who also are active birders both for identification as well as for Bird Photography. I am an retired active guy who loves birds and have been a birder since I was a teenager.",
    title: "ESerlin",
    author: "ESerlin",
    thumbnail: "assets/images/birdsplash/boris-smokrovic-200388-unsplash.png",
    reviews: 1
  },
  {
    initial: "R",
    lastName: "Abraham",
    area: "Christiansburg",
    state: "VA",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English",
    description: "I live in an area where there are small towns. Blacksburg and Christiansburg and Radford, Virginia. Blacksburg is the home of the largest University in the State. Radford is the host to a smaller University, Radford. As Radford parallels New River there are ample opportunities to bird in our area. There are also birding trails in both Blacksburg and in Radford. These are a part of the Virginia Birding trail system. I have a small Jon boat and I am willing to take a fellow birder on a river trip. However I will not be interested in taking any person birding who smokes. I am an avid bird watcher as well as a photographer. When I go on trips I will always take a camera with me. I will always be more than willing to answer any inquiries that folks would like to know about the area where I live. I belong to the New River Bird Club and have many friends who also are active birders both for identification as well as for Bird Photography. I am an retired active guy who loves birds and have been a birder since I was a teenager.",
    comments: "",
    title: "SGill",
    author: "SGill",
    thumbnail: "assets/images/birdsplash/brian-kraus-1190031-unsplash.png",
    reviews: 3
  },
  {
    initial: "K",
    lastName: "Mills",
    area: "Church Falls",
    state: "VA",
    available: "Weekend",
    interests: "Birding by Ear",
    language: "English",
    description: "I am located near Jordan Lake. An outstanding birding location year-round, Jordan Lake seems to attract more stellar rarities, such as Long-billed Murrelet, White-tailed Tropicbird, and Smith's Longspur, than any other local spot. Jordan Lake has 13,900 acres of water to scan, nine state recreation areas, and more Bald Eagles than you can shake a stick at.",
    comments: "",
    title: "RAbraham",
    author: "RAbraham",
    thumbnail: "assets/images/birdsplash/bruce-jastrow-462393-unsplash.png",
    reviews: 4
  },
  {
    initial: "M",
    lastName: "James",
    area: "Columbia",
    state: "MD",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "I work at a biological lab but not with birds. Amateur birder. 2 eagle nests water birds on lakes and saltwater Washington Capital parks many habitats",
    comments: "I work at a biological lab but not with birds. Amateur birder. 2 eagle nests water birds on lakes and saltwater Washington Capital parks many habitats",
    title: "MBrazeau",
    author: "MBrazeau",
    thumbnail: "assets/images/birdsplash/bruce-jastrow-675106-unsplash.png",
    reviews: 5
  },
  {
    initial: "G",
    lastName: "Weinberger",
    area: "Doswell",
    state: "VA",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "Highland County is well-known to birders. In the winter, you can see Golden Eagles, Rough-legged Hawks and other more northern species. Also a real hot spot during migration. I have a cottage for rent (reasonal rates) and am willing to show you where to go to see birds.",
    comments: "Highland County is well-known to birders. In the winter, you can see Golden Eagles, Rough-legged Hawks and other more northern species. Also a real hot spot during migration. I have a cottage for rent (reasonal rates) and am willing to show you where to go to see birds.",
    title: "KMills",
    author: "KMills",
    thumbnail: "assets/images/birdsplash/carlos-martinez-772873-unsplash.png",
    reviews: 1
  },
  {
    initial: "K",
    lastName: "Wouk",
    area: "Durham",
    state: "",
    available: "Weekend",
    interests: "Warblers",
    language: "English, some Spanish",
    description: "I am not an expert but serve on our local Audubon board with a lot of them! If there is a specific bird or birds that you would like to see I am sure I can find out where to go. I am in the Raleigh/Durham area (middle of the state). We have lots of very cool birds.",
    comments: "I am located near Jordan Lake. An outstanding birding location year-round, Jordan Lake seems to attract more stellar rarities, such as Long-billed Murrelet, White-tailed Tropicbird, and Smith's Longspur, than any other local spot. Jordan Lake has 13,900 acres of water to scan, nine state recreation areas, and more Bald Eagles than you can shake a stick at.",
    title: "MCooper",
    author: "MCooper",
    thumbnail: "assets/images/birdsplash/chris-charles-558521-unsplash.png",
    reviews: 5
  },
  {
    initial: "K",
    lastName: "Reichart",
    area: "Durham",
    state: "NC",
    available: "Weekend",
    interests: "Photography",
    language: "English, Spanish",
    description: "I am located near Jordan Lake. An outstanding birding location year-round, Jordan Lake seems to attract more stellar rarities, such as Long-billed Murrelet, White-tailed Tropicbird, and Smith's Longspur, than any other local spot. Jordan Lake has 13,900 acres of water to scan, nine state recreation areas, and more Bald Eagles than you can shake a stick at.",
    comments: "There are about as many birdwatchers as birds around here, so if I happen to be busy (which has been the case lately) there is likely to be somebody else available to whom I could refer you. Southeastern US specialties: Brown-headed Nuthatch and Red-bellied Woodpecker are relatively easy to find year round. Most other species of special interest are seasonal.",
    title: "KWouk",
    author: "KWouk",
    thumbnail: "assets/images/birdsplash/chris-chow-712612-unsplash.png",
    reviews: 5
  },
  {
    initial: "S",
    lastName: "Winton",
    area: "Durham",
    state: "NC",
    available: "Weekend",
    interests: "Rare Birds",
    language: "English, Spanish",
    description: "There are about as many birdwatchers as birds around here, so if I happen to be busy (which has been the case lately) there is likely to be somebody else available to whom I could refer you. Southeastern US specialties: Brown-headed Nuthatch and Red-bellied Woodpecker are relatively easy to find year round. Most other species of special interest are seasonal.",
    comments: "",
    title: "KReichart",
    author: "KReichart",
    thumbnail: "assets/images/birdsplash/chris-leipelt-295662-unsplash.png",
    reviews: 4
  },
  {
    initial: "D",
    lastName: "Palmer",
    area: "Easton",
    state: "MD",
    available: "Weekend",
    interests: "Birding by Ear",
    language: "English",
    description: "The Eastern Shore of Maryland and Delaware, Blackwater National Wildlife Refuge (Bald Eagle capital of E. North America). I am an avid Wildlife photographer with an interest is birds.",
    comments: "",
    title: "DMoulton",
    author: "DMoulton",
    thumbnail: "assets/images/birdsplash/christin-hume-1286940-unsplash.png",
    reviews: 3
  },
  {
    initial: "K",
    lastName: "Harris",
    area: "Easton",
    state: "MD",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "Places within two hours: Chesapeake Bay, Atlantic Ocean, Bombay NWR, Blackwater NWR, Pickering Creek Audubon Center, Jean Ellen dePont Shehan Audubon Sancturay, Adkins Arboretum and Tuckahoe State Park. Will gladly respond to email.",
    comments: "",
    title: "JMusike",
    author: "JMusike",
    thumbnail: "assets/images/birdsplash/colin-watts-1185371-unsplash.png",
    reviews: 3
  },
  {
    initial: "P",
    lastName: "Thut",
    area: "Easton",
    state: "MD",
    available: "Anytime",
    interests: "Warblers",
    language: "English",
    description: "We regularly submit checklists to eBird. We live in Talbot County, Maryland, between Easton and St. Michaels. This is on Maryland’s Eastern Shore, approximately an hour from BWI Airport in Baltimore and the same from Washington, DC. Approximately 260 species are seen in Talbot County each year. Our area is not strong for warbler migration, but is excellent for wintering waterfowl. The Blackwater NWR is about an hour away and the Bombay Hook NWR in Delaware is an hour and a half in the other direction. Both are excellent places to bird in the cooler months. We would be happy to offer location advice to visitors and would be willing to accompany them if we are at home. Our local Bird Club also welcomes visitors on our Sunday morning walks.",
    comments: "Eastern shore area of Maryland, Marsh birds, ducks, beach birds in area, Eagles, cranes, swans, ospray, doves, turkey, song birds close to many hotels in our town. State and FED park near by on Assatigue Island and lots of public land, E.A. Vaun area, Pocamoke State Park, and Ward brothers center for duck lovers only 30 min away.",
    title: "NKahn",
    author: "NKahn",
    thumbnail: "assets/images/birdsplash/deion-reaves-394134-unsplash.png",
    reviews: 1
  },
  {
    initial: "S",
    lastName: "Nelson",
    area: "Frederick",
    state: "MD",
    available: "Anytime",
    interests: "Photography",
    language: "English",
    description: "I really like photography, and am blank to birding. The listed local birding clubs are at a minimum of two hours or more away, so it's not feasible for me to meet with them, but I know I need the guidance of an experienced birder. I'm a Marine so scheduling can work out to where I have free weekdays, but I can't really highlight Anytime due to the unpredictability of my weekday schedule. As far as being located next to major birding areas goes, I live in the North Carolina Outer Banks so there's tons of places to bird where I live.",
    comments: "",
    title: "RCantilli",
    author: "RCantilli",
    thumbnail: "assets/images/birdsplash/dennis-buchner-435432-unsplash.png",
    reviews: 1
  },
  {
    initial: "M",
    lastName: "Reinsel",
    area: "Greenbelt, Maryland",
    state: "MD",
    available: "Weekends",
    interests: "Rare Birds",
    language: "English",
    description: "I work at a biological lab but not with birds. Amateur birder. 2 eagle nests water birds on lakes and saltwater Washington Capital parks many habitats",
    comments: "",
    title: "MJames",
    author: "MJames",
    thumbnail: "assets/images/birdsplash/dominik-lange-389363-unsplash.png",
    reviews: 2
  },
  {
    initial: "D",
    lastName: "Burnette",
    area: "Greensboro",
    state: "NC",
    available: "Anytime",
    interests: "Birding by Ear",
    language: "English, German, French, Japanese, some Spanish",
    description: "Greensboro is in the approximate geographic center of North Carolina in Guilford County. While there are few rarities here, it is a good area in which to see nearly all of the typical southeastern bird species. Birds have been well documented in the county since the late 1930s by an active local bird club. I am a retired educator, an amateur naturalist, and a wildlife photographer interested in birds, butterflies, dragonflies, wildflowers, and other wildlife of the area. My wife and I enjoy showing visitors our little corner of the world.",
    comments: "I really like photography, and am blank to birding. The listed local birding clubs are at a minimum of two hours or more away, so it's not feasible for me to meet with them, but I know I need the guidance of an experienced birder. I'm a Marine so scheduling can work out to where I have free weekdays, but I can't really highlight Anytime due to the unpredictability of my weekday schedule. As far as being located next to major birding areas goes, I live in the North Carolina Outer Banks so there's tons of places to bird where I live.",
    title: "ACoston",
    author: "ACoston",
    thumbnail: "assets/images/birdsplash/dominik-lange-41372-unsplash.png",
    reviews: 3
  },
  {
    initial: "A",
    lastName: "Rhodes",
    area: "Havelock",
    state: "NC",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "I really like photography, and am blank to birding. The listed local birding clubs are at a minimum of two hours or more away, so it's not feasible for me to meet with them, but I know I need the guidance of an experienced birder. I'm a Marine so scheduling can work out to where I have free weekdays, but I can't really highlight Anytime due to the unpredictability of my weekday schedule. As far as being located next to major birding areas goes, I live in the North Carolina Outer Banks so there's tons of places to bird where I live.",
    comments: "I live in the Piedmont area pf NC but grew up in the Coastal Plain/Sandhills area of NC. I am a member of Sylvan Heights Waterfowl Park which is within 90 miles from Raleigh. I go there a lot. They have close to 200 waterfowls and birds from all over the world. A wonderful place dedicated to the preservation of endangered species. I have traveled to the Gallapagos Islands and Costa Rica, studying and photographing birds. I have my tickets now for a trip to South Africa, namely Zambia, Namibia and Botswana. I am current working on the Cornell University course to learn more about birds and their behaviors. I have been carving realistic birds for 20 years and teach this art form to 30 students attending classes I hold regularly in my studio in Raleigh. My wesite: www.wildfowlart.com and I administer my website, www.birdcarversonline.com.",
    title: "DBurnette",
    author: "DBurnette",
    thumbnail: "assets/images/birdsplash/eder-pozo-perez-32854-unsplash.png",
    reviews: 4
  },
  {
    initial: "S",
    lastName: "Teague",
    area: "Hickory",
    state: "NC",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "Know some good sites in the Blue Ridge mountains and surrounding area.",
    comments: "I am a park ranger for Catawba County in the foothills of NC. I am also a bird bander.",
    title: "SWinton",
    author: "SWinton",
    thumbnail: "assets/images/birdsplash/gabriel-435509-unsplash.png",
    reviews: 1
  },
  {
    initial: "D",
    lastName: "Martin",
    area: "Hickory",
    state: "",
    available: "Anytime",
    interests: "Warblers",
    language: "English",
    description: "I am a park ranger for Catawba County in the foothills of NC. I am also a bird bander.",
    comments: "I have been birding for over 50 years and enjoy sharing my hobby with beginners and advanced birders. Western NC has a few specialties such as sawhet owl and red-crossbill, plus many warblers during migration.",
    title: "STeague",
    author: "STeague",
    thumbnail: "assets/images/birdsplash/gary-bendig-192233-unsplash.png",
    reviews: 3
  },
  {
    initial: "T",
    lastName: "Sinclair",
    area: "Hickory",
    state: "NC",
    available: "Anytime",
    interests: "Photography",
    language: "English",
    description: "I have been birding for over 50 years and enjoy sharing my hobby with beginners and advanced birders. Western NC has a few specialties such as sawhet owl and red-crossbill, plus many warblers during migration.",
    comments: "Located in the northwest piedmont of North Carolina, near Greensboro and Winston Salem. We are an hour away from the NC Zoo, Raleigh, Durham, and Chapel Hill, and an hour and a half away from the Blue Ridge Mountains, and Charlotte.",
    title: "DMartin",
    author: "DMartin",
    thumbnail: "assets/images/birdsplash/gary-bendig-192235-unsplash.png",
    reviews: 4
  },
  {
    initial: "L",
    lastName: "Hayes",
    area: "High Point",
    state: "NC",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English",
    description: "Located in the northwest piedmont of North Carolina, near Greensboro and Winston Salem. We are an hour away from the NC Zoo, Raleigh, Durham, and Chapel Hill, and an hour and a half away from the Blue Ridge Mountains, and Charlotte.",
    comments: "Know some good sites in the Blue Ridge mountains and surrounding area.",
    title: "TSinclair",
    author: "TSinclair",
    thumbnail: "assets/images/birdsplash/guilherme-romano-300844-unsplash.png",
    reviews: 5
  },
  {
    initial: "P",
    lastName: "Reum",
    area: "Highland County",
    state: "VA",
    available: "Weekend",
    interests: "Birding by Ear",
    language: "English",
    description: "Highland County is well-known to birders. In the winter, you can see Golden Eagles, Rough-legged Hawks and other more northern species. Also a real hot spot during migration. I have a cottage for rent (reasonal rates) and am willing to show you where to go to see birds.",
    comments: "West of Richmond, VA; wooded areas, flat, some marsh, near large river. Good winter and spring birds. Amateur; several international trips. Just for fun.",
    title: "GWeinberger",
    author: "GWeinberger",
    thumbnail: "assets/images/birdsplash/hans-eiskonen-25805-unsplash.png",
    reviews: 1
  },
  {
    initial: "J",
    lastName: "Artes",
    area: "Indian Head",
    state: "MD",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "I have served on the Southern Maryland Audubon Society Board on two occasions and am currently a member of the education committee. I have participated in May and Christmas counts for over 15 years. I would be happy to give locations information and when I can accompany them to local areas. I live in Charles County with border on the Potomac River. It contains various creeks, swamps, streams and ponds. Several wildlife management areas/state parks in my area.",
    comments: "I'm about 15 minutes from the National Arboretum and close to several parks and wildlife refuges. Great areas for spring migration (late April- early May: warblers, orioles, tanagers, hawks, etc) and for waterfowl in the winters.",
    title: "JLanders",
    author: "JLanders",
    thumbnail: "assets/images/birdsplash/hawin-rojas-7968-unsplash.png",
    reviews: 5
  },
  {
    initial: "R",
    lastName: "Doyle",
    area: "Laurel",
    state: "MD",
    available: "Anytime",
    interests: "Warblers",
    language: "English",
    description: "Eastern shore area of Maryland, Marsh birds, ducks, beach birds in area, Eagles, cranes, swans, ospray, doves, turkey, song birds close to many hotels in our town. State and FED park near by on Assatigue Island and lots of public land, E.A. Vaun area, Pocamoke State Park, and Ward brothers center for duck lovers only 30 min away.",
    comments: "I've been birding for nearly 30 years and consider myself a good to excellent birder. I live right outside Great Falls Park which is excellent for birding - many habitats and loads of water with the Potomac River and CO canal nearby. If people want to see Bald Eagles and Great Blue heron as well as Baltimore Orioles, Barred Owls, Yellow-throated Vireos, this is the place to see them. Plus there's the opportunity to see Great Falls and some historical sites in the park - the old tavern, the lock and barge system from the early 1800s.",
    title: "PThut",
    author: "PThut",
    thumbnail: "assets/images/birdsplash/iftikhar-shah-16190-unsplash.png",
    reviews: 5
  },
  {
    initial: "D",
    lastName: "Johnston",
    area: "Leicester",
    state: "NC",
    available: "Anytime",
    interests: "Photography",
    language: "English",
    description: "Know some good sites in the Blue Ridge mountains and surrounding area.",
    comments: "I'm an intermediate birder and very knowledgeable about where and when to find birds in North Carolina.",
    title: "LHayes",
    author: "LHayes",
    thumbnail: "assets/images/birdsplash/john-duncan-1187278-unsplash.png",
    reviews: 4
  },
  {
    initial: "C",
    lastName: "Metzgar",
    area: "Manakin Sabot",
    state: "VA",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English some Spanish",
    description: "West of Richmond, VA; wooded areas, flat, some marsh, near large river. Good winter and spring birds. Amateur; several international trips. Just for fun.",
    comments: "",
    title: "PReum",
    author: "PReum",
    thumbnail: "assets/images/birdsplash/jon-sailer-1155936-unsplash.png",
    reviews: 3
  },
  {
    initial: "R",
    lastName: "Young",
    area: "McLean",
    state: "VA",
    available: "Weekend",
    interests: "Birding by Ear",
    language: "English",
    description: "I'm an intermediate birder and very knowledgeable about where and when to find birds in North Carolina.",
    comments: "I have been a birder for many years and love to show people new birds whenever I can. I am close to the coast and to several good birding spots. Lots of good waterfowl and ocean birds in the winter, and there are several good spots for migrating warblers and shorebirds.",
    title: "CMetzgar",
    author: "CMetzgar",
    thumbnail: "assets/images/birdsplash/joshua-wilking-386949-unsplash.png",
    reviews: 3
  },
  {
    initial: "J",
    lastName: "Stone",
    area: "Newport News",
    state: "VA",
    available: "Anytime",
    interests: "Hiking",
    language: "English, some Spanish",
    description: "I have been a birder for many years and love to show people new birds whenever I can. I am close to the coast and to several good birding spots. Lots of good waterfowl and ocean birds in the winter, and there are several good spots for migrating warblers and shorebirds.",
    comments: "",
    title: "RYoung",
    author: "RYoung",
    thumbnail: "assets/images/birdsplash/julian-jakob-strauss-1180576-unsplash.png",
    reviews: 2
  },
  {
    initial: "M",
    lastName: "Hurley",
    area: "Ocean City",
    state: "MD",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "Annapolis is on the Chesapeake Bay, a 45 minute drive from Washington DC and Baltimore, an hour and half to the Delaware Bay, and 2 hours to the Atlantic Ocean. I work Monday through Friday but spend many weekends and holidays birding locally or within the region. Best birding here is late Summer through Spring.",
    comments: "There are many areas within a short drive for the common East Coast species. In summer, there are yellow-crowned night herons in my neighborhood. This is a good area for those visiting D.C. and wanting to see many of America's East Coast birds for the first time. The coast, freshwater marsh, and salt marsh are only 2 hour drive away for the less common species. I have been an avid birder for about 8 years.",
    title: "MReinsel",
    author: "MReinsel",
    thumbnail: "assets/images/birdsplash/kalpesh-patel-786182-unsplash.png",
    reviews: 1
  },
  {
    initial: "C",
    lastName: "Perera",
    area: "Olney",
    state: "MD",
    available: "Weekend",
    interests: "Warblers",
    language: "English",
    description: "I lead trips for the Southern Maryland Audubon Society. I am very experienced with bird-finding in this region, which is a wonderful birding area. I know what a tremendous help it has been to me to have a local guide in new territory. I hope I can help.",
    comments: "I lead trips for the Southern Maryland Audubon Society. I am very experienced with bird-finding in this region, which is a wonderful birding area. I know what a tremendous help it has been to me to have a local guide in new territory. I hope I can help.",
    title: "BKlick",
    author: "BKlick",
    thumbnail: "assets/images/birdsplash/karl-kohler-508316-unsplash.png",
    reviews: 2
  },
  {
    initial: "J",
    lastName: "Harris",
    area: "Orlean, Virginia, USA",
    state: "VA",
    available: "Sundays and Mondays. Other times possible.",
    interests: "Photography",
    language: "English, Spanish, Indonesian (coversational)",
    description: "Near the Croatan National Forest. In Summer Painted Buntings are seen on the coast. A couple of hours from Lake Mattamuskeet, a major wintering ground for Tundra Swans from Nov. 15 thru Feb. 15.",
    comments: "",
    title: "JStone",
    author: "JStone",
    thumbnail: "assets/images/birdsplash/katerina-kerdi-414617-unsplash.png",
    reviews: 3
  },
  {
    initial: "E",
    lastName: "Carlson",
    area: "Pasadena",
    state: "MD",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English",
    description: "I am familiar with Northern Anne Arundel County birding sites such as Swan Creek and Fort Smallwood Park and some other sites and birds that are common in Maryland.",
    comments: "Annapolis is on the Chesapeake Bay, a 45 minute drive from Washington DC and Baltimore, an hour and half to the Delaware Bay, and 2 hours to the Atlantic Ocean. I work Monday through Friday but spend many weekends and holidays birding locally or within the region. Best birding here is late Summer through Spring.",
    title: "DLeonnig",
    author: "DLeonnig",
    thumbnail: "assets/images/birdsplash/kyle-szegedi-55847-unsplash.png",
    reviews: 4
  },
  {
    initial: "R",
    lastName: "Cantilli",
    area: "Potomac",
    state: "MD",
    available: "Anytime",
    interests: "Birding by Ear",
    language: "English\nintermediate Italian\nsome Spanish",
    description: "I've been birding for nearly 30 years and consider myself a good to excellent birder. I live right outside Great Falls Park which is excellent for birding - many habitats and loads of water with the Potomac River and CO canal nearby. If people want to see Bald Eagles and Great Blue heron as well as Baltimore Orioles, Barred Owls, Yellow-throated Vireos, this is the place to see them. Plus there's the opportunity to see Great Falls and some historical sites in the park - the old tavern, the lock and barge system from the early 1800s.",
    comments: "",
    title: "RDoyle",
    author: "RDoyle",
    thumbnail: "assets/images/birdsplash/m-zonderling-365891-unsplash.png",
    reviews: 1
  },
  {
    initial: "C",
    lastName: "Kessler",
    area: "Radford",
    state: "VA",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "I spend most of my free days hiking, car birding, and photographing birds and other wildlife in western NC. I know many of the great areas to see migrating, wintering and breeding birds and my wife and I would love to share those places with you.",
    comments: "",
    title: "JHarris",
    author: "JHarris",
    thumbnail: "assets/images/birdsplash/matheus-queiroz-298503-unsplash.png",
    reviews: 3
  },
  {
    initial: "J",
    lastName: "Southern",
    area: "Raleigh",
    state: "NC",
    available: "Anytime",
    interests: "Warblers",
    language: "English",
    description: "I'm an intermediate birder and very knowledgeable about where and when to find birds in North Carolina.",
    comments: "I lead most of the birding trips for Wake Audubon Society's Meetup Group (local Wake County areas). I also enjoy birding at Mason Farm (Chapel Hill) and Howell Woods ((Johnston Co). I work Mon-Thurs so my best times are Fri-Sat-Sun, but I might be able to do short trips in the midweek too.",
    title: "DJohnston",
    author: "DJohnston",
    thumbnail: "assets/images/birdsplash/melody-p-474181-unsplash.png",
    reviews: 4
  },
  {
    initial: "L",
    lastName: "Beegle",
    area: "Raleigh",
    state: "NC",
    available: "Anytime",
    interests: "Photography",
    language: "English",
    description: "I lead most of the birding trips for Wake Audubon Society's Meetup Group (local Wake County areas). I also enjoy birding at Mason Farm (Chapel Hill) and Howell Woods ((Johnston Co). I work Mon-Thurs so my best times are Fri-Sat-Sun, but I might be able to do short trips in the midweek too.",
    comments: "Near the Croatan National Forest. In Summer Painted Buntings are seen on the coast. A couple of hours from Lake Mattamuskeet, a major wintering ground for Tundra Swans from Nov. 15 thru Feb. 15.",
    title: "JSouthern",
    author: "JSouthern",
    thumbnail: "assets/images/birdsplash/mikhail-vasilyev-17211-unsplash.png",
    reviews: 5
  },
  {
    initial: "V",
    lastName: "Kirkman",
    area: "Raleigh",
    state: "NC",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English",
    description: "I live in the Piedmont area pf NC but grew up in the Coastal Plain/Sandhills area of NC. I am a member of Sylvan Heights Waterfowl Park which is within 90 miles from Raleigh. I go there a lot. They have close to 200 waterfowls and birds from all over the world. A wonderful place dedicated to the preservation of endangered species. I have traveled to the Gallapagos Islands and Costa Rica, studying and photographing birds. I have my tickets now for a trip to South Africa, namely Zambia, Namibia and Botswana. I am current working on the Cornell University course to learn more about birds and their behaviors. I have been carving realistic birds for 20 years and teach this art form to 30 students attending classes I hold regularly in my studio in Raleigh. My wesite: www.wildfowlart.com and I administer my website, www.birdcarversonline.com.",
    comments: "I spend most of my free days hiking, car birding, and photographing birds and other wildlife in western NC. I know many of the great areas to see migrating, wintering and breeding birds and my wife and I would love to share those places with you.",
    title: "ARhodes",
    author: "ARhodes",
    thumbnail: "assets/images/birdsplash/miroslava-274907-unsplash.png",
    reviews: 1
  },
  {
    initial: "M",
    lastName: "O'Bryan",
    area: "Richmond",
    state: "VA",
    available: "Anytime",
    interests: "Birding by Ear",
    language: "English",
    description: "Near Staunton River State Park, Staunton River Battlefield State Park, Buggs Island Lake (known as Kerr Lake in North Carolina). Only about an hour and a half from the mountains of Virginia.",
    comments: "",
    title: "CKessler",
    author: "CKessler",
    thumbnail: "assets/images/birdsplash/norbert-kundrak-1199043-unsplash.png",
    reviews: 5
  },
  {
    initial: "B",
    lastName: "Adams",
    area: "Richmond",
    state: "VA",
    available: "Anytime",
    interests: "Hiking",
    language: "English, French",
    description: "Not the best place in United States, but is good during spring and fall migration.",
    comments: "Available, when I do not have any wild birds that I am rehabbing. Local Roanoke and local hot spots within 20/30 miles. Will answer questions about injured wild birds.",
    title: "MO'Bryan",
    author: "MO'Bryan",
    thumbnail: "assets/images/birdsplash/olesya-grichina-234200-unsplash.png",
    reviews: 5
  },
  {
    initial: "M",
    lastName: "Eiger",
    area: "Roanoke",
    state: "VA",
    available: "Anytime",
    interests: "Hiking",
    language: "English",
    description: "Available, when I do not have any wild birds that I am rehabbing. Local Roanoke and local hot spots within 20/30 miles. Will answer questions about injured wild birds.",
    comments: "Shenandoah National Park, Staunton, Waynesboro, and Harrisonburg areas are my home areas. I know locations for breeding Cerulean Warblers, wintering waterfowl, and much else.",
    title: "BAdams",
    author: "BAdams",
    thumbnail: "assets/images/birdsplash/paolo-nicolello-479462-unsplash.png",
    reviews: 4
  },
  {
    initial: "G",
    lastName: "Mapel",
    area: "Shenandoah Valley, zip 24469",
    state: "VA",
    available: "Anytime",
    interests: "Warblers",
    language: "English",
    description: "Shenandoah National Park, Staunton, Waynesboro, and Harrisonburg areas are my home areas. I know locations for breeding Cerulean Warblers, wintering waterfowl, and much else.",
    comments: "Near Staunton River State Park, Staunton River Battlefield State Park, Buggs Island Lake (known as Kerr Lake in North Carolina). Only about an hour and a half from the mountains of Virginia.",
    title: "MEiger",
    author: "MEiger",
    thumbnail: "assets/images/birdsplash/pascal-mauerhofer-424286-unsplash.png",
    reviews: 3
  },
  {
    initial: "N",
    lastName: "Kahn",
    area: "Silver Spring",
    state: "MD",
    available: "Weekend",
    interests: "Photography",
    language: "English",
    description: "There are many areas within a short drive for the common East Coast species. In summer, there are yellow-crowned night herons in my neighborhood. This is a good area for those visiting D.C. and wanting to see many of America's East Coast birds for the first time. The coast, freshwater marsh, and salt marsh are only 2 hour drive away for the less common species. I have been an avid birder for about 8 years.",
    comments: "We regularly submit checklists to eBird. We live in Talbot County, Maryland, between Easton and St. Michaels. This is on Maryland’s Eastern Shore, approximately an hour from BWI Airport in Baltimore and the same from Washington, DC. Approximately 260 species are seen in Talbot County each year. Our area is not strong for warbler migration, but is excellent for wintering waterfowl. The Blackwater NWR is about an hour away and the Bombay Hook NWR in Delaware is an hour and a half in the other direction. Both are excellent places to bird in the cooler months. We would be happy to offer location advice to visitors and would be willing to accompany them if we are at home. Our local Bird Club also welcomes visitors on our Sunday morning walks.",
    title: "MHurley",
    author: "MHurley",
    thumbnail: "assets/images/birdsplash/patrycja-polechonska-123496-unsplash.png",
    reviews: 3
  },
  {
    initial: "R",
    lastName: "Johnson",
    area: "Smoky Mountains, North Carolina",
    state: "NC",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English",
    description: "I spend most of my free days hiking, car birding, and photographing birds and other wildlife in western NC. I know many of the great areas to see migrating, wintering and breeding birds and my wife and I would love to share those places with you.",
    comments: "Not the best place in United States, but is good during spring and fall migration.",
    title: "VKirkman",
    author: "VKirkman",
    thumbnail: "assets/images/birdsplash/patrycja-polechonska-125879-unsplash.png",
    reviews: 4
  },
  {
    initial: "J",
    lastName: "Blalock",
    area: "South Boston",
    state: "VA",
    available: "Anytime",
    interests: "Birding by Ear",
    language: "English",
    description: "Near Staunton River State Park, Staunton River Battlefield State Park, Buggs Island Lake (known as Kerr Lake in North Carolina). Only about an hour and a half from the mountains of Virginia.",
    comments: "Been birding for twenty plus years. Do bird surveys for the Forest Service.",
    title: "GMapel",
    author: "GMapel",
    thumbnail: "assets/images/birdsplash/paulo-brandao-1001-unsplash.png",
    reviews: 1
  },
  {
    email:"lylekarim+12@gmail.com",
    password:"password",
    initial: "D",
    lastName: "Holsinger",
    area: "Timberville",
    state: "VA",
    available: "Anytime",
    interests: "Hiking",
    language: "English, some Spanish",
    description: "Been birding for twenty plus years. Do bird surveys for the Forest Service.",
    comments: "I have been birding for 10+ years. I am a member of the Northern Virginia Bird Club and previously a member of Potomac Valley Audubon Society, where I used to live. I currently travel for work and have had the chance to bird in Italy, Austria, Singapore, and Seoul. I have birded with birding pals in San Francisco and Vienna this year and would like to get the chance to go birding with visitors of N. VA or even DC.",
    title: "JBlalock",
    author: "JBlalock",
    thumbnail: "assets/images/birdsplash/quentin-dr-169842-unsplash.png",
    reviews: 2
  },
  {
    email:"lylekarim+13@gmail.com",
    password:"password",
    initial: "J",
    lastName: "Smith",
    area: "Trenton",
    state: "NC",
    available: "Anytime",
    interests: "Warblers",
    language: "English, some Spanish",
    description: "Near the Croatan National Forest. In Summer Painted Buntings are seen on the coast. A couple of hours from Lake Mattamuskeet, a major wintering ground for Tundra Swans from Nov. 15 thru Feb. 15.",
    comments: "",
    title: "LBeegle",
    author: "LBeegle",
    thumbnail: "assets/images/birdsplash/ray-hennessy-1134702-unsplash.png",
    reviews: 3
  },
  {
    email:"lylekarim+14@gmail.com",
    password:"password",
    initial: "D",
    lastName: "Leonnig",
    area: "Upper Marlboro",
    state: "MD",
    available: "Anytime",
    interests: "Photography",
    language: "English",
    description: "I am familiar with Northern Anne Arundel County birding sites such as Swan Creek and Fort Smallwood Park and some other sites and birds that are common in Maryland.",
    comments: "I am familiar with Northern Anne Arundel County birding sites such as Swan Creek and Fort Smallwood Park and some other sites and birds that are common in Maryland.",
    title: "DPalmer",
    author: "DPalmer",
    thumbnail: "assets/images/birdsplash/ray-hennessy-126090-unsplash.png",
    reviews: 4
  },
  {
    email:"lylekarim+15@gmail.com",
    password:"password",
    initial: "L",
    lastName: "Meade",
    area: "Vienna",
    state: "VA",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English",
    description: "I am an active birder and photographer who often leads trips for the Northern Virginia Bird Club. This area has many birdy locations especially during migration.",
    comments: "Most parks like Shenandoah National Park. Like hiking trails. Hawk MT.PA -and WV some.",
    title: "JGozart",
    author: "JGozart",
    thumbnail: "assets/images/birdsplash/ray-hennessy-178367-unsplash.png",
    reviews: 1
  },
  {
    email:"lylekarim+16@gmail.com",
    password:"password",
    initial: "M",
    lastName: "Hillman",
    area: "Wallops Island",
    state: "VA",
    available: "Weekends (generally Friday and Saturday), Open to other days.",
    interests: "Birding by Ear",
    language: "English",
    description: "I am a young professional with a passion for birding and nature. My background is in the zoo and aquarium field, where I have spent the last 6 years working as an educator, presenter, tour leader, and zookeeper. Currently, I coordinate and lead educational programs on the Eastern Shore of Virginia, including as a Birding Guide for Road Scholar. I am avid birder, though with a degree in Zoology I can get just as excited by any other class of animal. I'm always trying to add species to my bird/mammal/reptile/amphibian/fish lists and that gets me outdoors and traveling as much as possible in my spare time. If you are looking for adventure on a long trek or simply some easy birding at a couple prime local spots, I would love to take you out in the Delmarva region. Happy Birding!",
    comments: "I have been an active birder for thirty years. I would consider myself an expert on local birding topics. I feed the birds at my house with every feed our local birds might need.",
    title: "TBrill",
    author: "TBrill",
    thumbnail: "assets/images/birdsplash/ray-hennessy-229598-unsplash.png",
    reviews: 3
  },
  {
    email:"lylekarim+17@gmail.com",
    password:"password",
    initial: "J",
    lastName: "Gozart",
    area: "Warrenton (Northern VA)",
    state: "VA",
    available: "Weekend",
    interests: "Hiking",
    language: "English",
    description: "I have been birding for 10+ years. I am a member of the Northern Virginia Bird Club and previously a member of Potomac Valley Audubon Society, where I used to live. I currently travel for work and have had the chance to bird in Italy, Austria, Singapore, and Seoul. I have birded with birding pals in San Francisco and Vienna this year and would like to get the chance to go birding with visitors of N. VA or even DC.",
    comments: "I am an active birder and photographer who often leads trips for the Northern Virginia Bird Club. This area has many birdy locations especially during migration.",
    title: "DHolsinger",
    author: "DHolsinger",
    thumbnail: "assets/images/birdsplash/ray-hennessy-253874-unsplash.png",
    reviews: 4
  },
  {
    email:"lylekarim+18@gmail.com",
    password:"password",
    initial: "J",
    lastName: "Dorothy",
    area: "Washington DC metro area",
    state: "MD",
    available: "Weekend",
    interests: "Hiking",
    language: "English, some Spanish",
    description: "I'm about 15 minutes from the National Arboretum and close to several parks and wildlife refuges. Great areas for spring migration (late April- early May: warblers, orioles, tanagers, hawks, etc) and for waterfowl in the winters.",
    comments: "I am not a professional bird guide but run a professional charter sailboat. I think bird watchers would really enjoy both. We see ospreys, eagles, herons, egrets, and a host of other birds, both water and land, migrating and resident. You can find my bio and rates at www.experiencesail.com This is a great way to view wildlife and spend time with family and friends.",
    title: "JArtes",
    author: "JArtes",
    thumbnail: "assets/images/birdsplash/ricardo-porto-272836-unsplash.png",
    reviews: 5
  },
  {
    email:"lylekarim+19@gmail.com",
    password:"password",
    initial: "C",
    lastName: "Jeschke",
    area: "Winchester",
    state: "VA",
    available: "Weekend",
    interests: "Warblers",
    language: "English",
    description: "Most parks like Shenandoah National Park. Like hiking trails. Hawk MT.PA -and WV some.",
    comments: "",
    title: "LMeade",
    author: "LMeade",
    thumbnail: "assets/images/birdsplash/richard-hoeg-116757-unsplash.png",
    reviews: 1
  },
  {
    email:"lylekarim+20@gmail.com",
    password:"password",
    initial: "T",
    lastName: "Brill",
    area: "Winchester",
    state: "VA",
    available: "Weekend",
    interests: "Photography",
    language: "English",
    description: "I am a young professional with a passion for birding and nature. My background is in the zoo and aquarium field, where I have spent the last 6 years working as an educator, presenter, tour leader, and zookeeper. Currently, I coordinate and lead educational programs on the Eastern Shore of Virginia, including as a Birding Guide for Road Scholar. I am avid birder, though with a degree in Zoology I can get just as excited by any other class of animal. I'm always trying to add species to my bird/mammal/reptile/amphibian/fish lists and that gets me outdoors and traveling as much as possible in my spare time. If you are looking for adventure on a long trek or simply some easy birding at a couple prime local spots, I would love to take you out in the Delmarva region. Happy Birding!",
    comments: "I am a young professional with a passion for birding and nature. My background is in the zoo and aquarium field, where I have spent the last 6 years working as an educator, presenter, tour leader, and zookeeper. Currently, I coordinate and lead educational programs on the Eastern Shore of Virginia, including as a Birding Guide for Road Scholar. I am avid birder, though with a degree in Zoology I can get just as excited by any other class of animal. I'm always trying to add species to my bird/mammal/reptile/amphibian/fish lists and that gets me outdoors and traveling as much as possible in my spare time. If you are looking for adventure on a long trek or simply some easy birding at a couple prime local spots, I would love to take you out in the Delmarva region. Happy Birding!",
    title: "CJeschke",
    author: "CJeschke",
    thumbnail: "assets/images/birdsplash/richard-lee-1176906-unsplash.png",
    reviews: 5
  },
  {
    email:"lylekarim+21@gmail.com",
    password:"password",
    initial: "B",
    lastName: "Sugg",
    area: "Winston-Salem",
    state: "NC",
    available: "Anytime",
    interests: "Rare Birds",
    language: "English",
    description: "I am an active birder and photographer who often leads trips for the Northern Virginia Bird Club. This area has many birdy locations especially during migration.",
    comments: "",
    title: "JSmith",
    author: "JSmith",
    thumbnail: "assets/images/birdsplash/richard-lee-518621-unsplash.png",
    reviews: 5
  },
  {
    email:"lylekarim+22@gmail.com",
    password:"password",
    initial: "F",
    lastName: "Shelton",
    area: "Winston-Salem",
    state: "NC",
    available: "Anytime",
    interests: "Birding by Ear",
    language: "English",
    description: "Winston-Salem is centrally located in NC, near Greensboro and High Point, and about 1.5 hours from Charlotte or Raleigh, NC.",
    comments: "Winston-Salem is centrally located in NC, near Greensboro and High Point, and about 1.5 hours from Charlotte or Raleigh, NC.",
    title: "BSugg",
    author: "BSugg",
    thumbnail: "assets/images/birdsplash/rod-long-47290-unsplash.png",
    reviews: 4
  },
];

db.Birder
  .remove({})
  .then(() => db.Birder.collection.insertMany(birdSeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
